
services:
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-service:
    build:
      context: .
      dockerfile: Dockerfile.api-services
    ports:
      - "3000:3000"
    depends_on:
      - db

  tree-service:
    build:
      context: .
      dockerfile: Dockerfile.tree-service
    environment:
      DB_TYPE: ${DB_TYPE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_PORT: ${PG_PORT}
      PG_HOST: db
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  pgdata: {}
